version: "3.9"
services:
  # client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    command: serve -s build
    volumes:
      - ./client/:/app/
  # server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod
    ports:
      - "8000:8000"
    command: gunicorn store.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/  
    depends_on:
    - db

  # database
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

  # proxy
  proxy:
    image: nginx
    ports:
      - "80:80"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/etc/nginx/conf.d/
      - /etc/ssl/certs:/etc/ssl/certs/
      - /etc/ssl/private:/etc/ssl/private/
    links:
      - server
      - client

volumes:
  postgres_data:
