version: "3.9"
services:
  # proxy
  proxy:
    image: nginx
    ports:
      - "80:80"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/etc/nginx/conf.d
      - /etc/ssl/certs:/etc/ssl/certs
      - /etc/ssl/private:/etc/ssl/private
  # client
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    # command: npm run dev --host
    volumes:
      - ./client/:/app/
  # server
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod
    ports:
      - "8000:8000"
    command: gunicorn store.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./server/:/usr/src/app/  
    depends_on:
    - db
    - wdb
    environment:
      WDB_SOCKET_SERVER: wdb
      WDB_NO_BROWSER_AUTO_OPEN: "true"
    stdin_open: true
    tty: true

  # database
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db.prod

  # debugger
  wdb:
    image: kozea/wdb
    ports:
      - 1984:1984
    # HACK https://github.com/Kozea/wdb/issues/136
    init: true

volumes:
  postgres_data:
